name:                haskell-sudoku-solver
version:             0.1.0.0
github:              eli-jordan/haskell-sudoku-solver
license:             BSD3
author:              Elias Jordan
maintainer:          example@example.com
copyright:           2018 Elias Jordan

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Sudoku solver in haskell

description:         Please see the README on Github at <https://github.com/eli-jordan/haskell-sudoku-solver>

dependencies:
- base >= 4.7 && < 5
- vector
- matrix
- split
- text
- containers
- tasty
- tasty-hunit

library:
  source-dirs: src

executables:
  haskell-sudoku-solver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-sudoku-solver

tests:
  haskell-sudoku-solver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-sudoku-solver
